Add memcache module
alibabacloud-automation/terraform-alicloud-memcache pull request #1
Opened 2020-02-05 10:02 UTC by Rich-yi

2020-02-13 07:39 UTC, zql-tqy commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[memcache云数据库](https://help.aliyun.com/document_detail/26342.html).
这个地址不是产品的吧

2020-02-13 07:39 UTC, zql-tqy commented on README-CN.md
> +* 本 Module 使用的 AccessKey 和 SecretKey 可以直接从 `profile` 和 `shared_credentials_file` 中获取。如果未设置，可通过下载安装 [aliyun-cli](https://github.com/aliyun/aliyun-cli#installation) 后进行配置.
标点

2020-02-13 07:39 UTC, zql-tqy commented on examples/complete/README.md
> +<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
这行也没有用吧

2020-02-13 07:39 UTC, zql-tqy commented on main.tf
> +  // availability_zone=var.availability_zone
没用删掉吧

2020-02-13 07:39 UTC, zql-tqy commented on modules/memcache/main.tf
> +  version                 = ">=1.68.0"
删掉

2020-02-13 07:39 UTC, zql-tqy commented on modules/memcache/variables.tf
> +  default     = ""
这个都没加type

2020-02-13 07:39 UTC, zql-tqy commented on variables.tf
> +  description = "The Id of an existing memcache instance. If set, the `create_instance` will be ignored."
`create_instance`  换'create_instance'

2020-02-14 02:49 UTC, xiaozhu36 requested changes

2020-02-14 02:49 UTC, xiaozhu36 commented on LICENSE
> +   4. memcachetribution. You may reproduce and distribute copies of the
这个为啥要改

2020-02-14 02:49 UTC, xiaozhu36 commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12 和阿里云 Provider 1.68.0+。
为什么是 1.68.0

2020-02-14 02:49 UTC, xiaozhu36 commented on README-CN.md
> +* [社区 Memcache](https://github.com/terraform-alicloud-modules/terraform-alicloud-memcache/tree/master/modules/memcache)
什么叫社区 memcache

2020-02-14 02:49 UTC, xiaozhu36 commented on main.tf
> +  engine_version        = "2.8"
现在只支持 2.8 么

2020-02-14 02:49 UTC, xiaozhu36 commented on variables.tf
> +  description = "The vswitch id used to launch one or more instances."
你这个里面就创建一个实例吧，怎么会有more 呢

2020-02-14 02:49 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
设置一个default值：tf-module-memcache

2020-02-14 02:49 UTC, xiaozhu36 commented on modules/memcache/main.tf
> +module "memcache" {
感觉这个子module跟主module没啥区别，如果没必要，直接去了吧

2020-02-14 03:13 UTC, Rich-yi commented on main.tf
> +  engine_version        = "2.8"
是的现在memcache只支持一个2.8的版本

2020-02-14 03:48 UTC, xiaozhu36 requested changes

2020-02-14 03:48 UTC, xiaozhu36 commented on README-CN.md
> +  engine_version       = "2.8"
module有这两个参数么？

2020-02-14 03:48 UTC, xiaozhu36 commented on examples/complete/outputs.tf
> +  description = "This memcache instance engine version ."
最后多了一个空格

2020-02-14 03:48 UTC, xiaozhu36 commented on examples/complete/outputs.tf
> +  description = "Whether to renewal a DB instance automatically or not."
这个描述不对吧

2020-02-14 03:48 UTC, xiaozhu36 commented on examples/complete/outputs.tf
> +  description = "The ID of the alarm rule. "
多了一个空格，其他的都检查下

2020-02-14 09:01 UTC, xiaozhu36 requested changes

2020-02-14 09:01 UTC, xiaozhu36 commented on main.tf
> +  count   = local.create_more_resources ? 1 : 0
这个alarm的count不对吧，应该是 create_more_resources 和 enable_alarm_rule 同时控制

2020-02-14 09:24 UTC, xiaozhu36 approved these changes

2020-02-14 09:24 UTC, merged